In [1]:
import numpy as np

In [13]:

# 1. Create an random array  values between 1 and 51
arr = np.random.randint(1,51,50).reshape(5,10)

#2 Create an 3x3 identity matrix

ident = np.identity(n=3)

print(ident)


# create an diagonal matrix

diag = np.diag([1,2,3,4],k=-1)

print(diag.shape)


print(diag)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(5, 5)
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
ar2 = np.arange(25).reshape(5,5)


print(ar2)

#extracting a submatrix
print(ar2[0:2,0:2])



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1]
 [5 6]]


In [ ]:


ar3 = np.arange(20)

print(ar3)


#if  element is greater than 10, replace it with -1, otherwise  keep it same

#How np.where(condition, x, y) works

#It checks the condition element-wise:

#If True → take the value from x.

#If False → take the value from y.
ar3 = np.where(ar3 >10,-1,ar3)


print(ar3)
print

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

(x -xmin )/ (xmax-xmin)

In [ ]:
def min_max_normalize(arr):
    return (arr - np.min(arr) )/ (np.max(arr) - np.min(arr))

new_arr = np.arange(25)

new_arr =  (new_arr - np.min(arr) )/ (np.max(new_arr) - np.min(new_arr))

print(new_arr)





[-0.04166667  0.          0.04166667  0.08333333  0.125       0.16666667
  0.20833333  0.25        0.29166667  0.33333333  0.375       0.41666667
  0.45833333  0.5         0.54166667  0.58333333  0.625       0.66666667
  0.70833333  0.75        0.79166667  0.83333333  0.875       0.91666667
  0.95833333]


In [ ]:
A = np.array([[2,3],[4,-5]])
b= np.array([1,7]).reshape(-1,1)

#Solve system of Linear Equations
np.linalg.solve(A,b)


#Find an inverse of Matrix
A_inverse = np.linalg.inv(A)


#get the determinant of inverse matrix
print(np.linalg.det(A_inverse))


-0.04545454545454544


### What is numpy  why is it popular ?

1. Numpy is an open source library in python that is  mainly used for mathematical  operations.
It's fast performance is one of the things that has made it popular
Seamless integration with other libraries, such as sklarn, pandas,


### How does numpy differ from python lists ?

Numpy arrays are stored in one block in the memory and  it's homogenuous, meaning it can only store fixed size, same type data, which is one of the things that makes numpy arrays faster. As we can directly access the adress memories with numpy it increases access speed, and also  in numpy  vectorization feature allows as to perform  elementwise operations  in one go.

### What is broadcasting ?

Broadcasting in numpy enables us to perform elementwise operation between arrays of different sizes, by implicitly matching the array's dimensions


### What is vectorization
Vectorization allows us  perform element wise operations, with one operation , avoiding loops


### Can numpy hold different types of data

No, it can not, it will upcast elements to string for example if there is  string


### How do you efficiently store arrays with lots of zeros ?


When working with sparse data (many zeroes), scipy.sparse matrices reduce memory usage.


### How would you apply a function elementwise to numpy array ?
I would use np.vectorize()


### What are ufuncs in numpy?
np.add
np.sum
np.sqrt
np.min
np.max

Implemented in C → avoids Python overhead

Operate on contiguous memory → CPU vectorization, SIMD instructions

Avoid Python-level loops → each operation happens at the memory level

### Explain the difference between a shallow copy and a deep copy of a NumPy array.




### Shallow copy

In [ ]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
b = a.view()
b[0][1] =78
print(a)

[[ 1 78  3]
 [ 4  5  6]]


### Deep copy

In [43]:
a = np.array([1,2,3,4,5,6]).reshape(2,3)
b = a.copy()
b[0][1] =78
print(a)

[[1 2 3]
 [4 5 6]]


### Can a new element added to numpy array after array creation?
No

### Is SIMD used by NumPy?

Yes by using CPU SIMD type instruction, multiple elements can be modified with one CPU instruction

### In NumPy, how do I change the data type of an array?

In [ ]:
arr = np.array([4.1,2.3])
new_arr= arr.astype('i')
print(arr)
print(new_arr)

[4.1 2.3]
[4 2]


### How to create numpy array from a list ?

In [ ]:
list1 = [1,2,3,4,5,6]
np_array = np.array(list1)

### How to create a list from numpy array ?

In [ ]:
# Convert a numpy array to a Python list
my_list = np_array.tolist()
print(my_list)

### How to reverse numpy array ?


arr = np.array([1,2,3,4,5,6])
reversed_arr = arr[::-1]
print(reversed_arr)


### How do you find the unique elements in numpy array

In [48]:
arr = np.array([1,1,1,2,3,4,5,6,6,7])
unique_elems=  np.unique(arr)
print(unique_elems)

[1 2 3 4 5 6 7]


### Write a NumPy function to get the maximum value from each column of a 2D array.

In [ ]:
arr = np.array([1,2,3,4,5,6]).reshape(2,3)
column_max = np.max(arr,axis=0)
print(arr)
print(column_max)

[[1 2 3]
 [4 5 6]]
[4 5 6]


### Numpy functions that return indices
1.np.where()

2.np.nonzero()

3.np.argmax()

4.np.argmin()

### How do you filter numpy array ?

In [ ]:
arr = np.array([1,2,3,4,5,65])
mask = arr <3
## boolean mask  True and Falses
print(mask)
# Applying the masking
print(arr[mask])
#replacing the values
arr[mask] = [0,0]
arr[mask] = 0


print(arr)


[ True  True False False False False]
[1 2]
[ 0  0  3  4  5 65]
